config/routes.rb
Dt10::Application.routes.draw do
  resources :notices

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

  resources :events do
    collection do
      get 'tomorrow'
      get 'popular'
      get 'recent'
      get 'search'
      get 'today'
      get 'date'
      get 'please_confirm'
    end
  end 

  get "home/index"    

  root :to => 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :page_views, :description, :location, :name, :eventdate, :eventtime


  def self.search(search)
    if search
      find(:all, :conditions => ['name ILIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

  belongs_to :user, :foreign_key => "user_id"

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  attr_accessible :contact, :description, :location, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :email_regexp => /.+@pitt.edu$/i

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery 
  def after_sign_in_path_for(resource)
    "/events"    
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

 #before_filter :authenticate_user! 
 
 def index
    @events = Event.find(:all, :order => 'page_views DESC', :limit => 10, :conditions => ["DATE(eventdate) BETWEEN ? AND ?", Date.today, Date.today + 30])
	   
    respond_to do |format|
      format.html # index.html.erb popular events
      format.json { render :json => @events }
    end
  end

  def search
    @events = Kaminari.paginate_array(Event.search(params[:search])).page(params[:page]).per(10)

    respond_to do |format|
      format.html # search.html.erb
      format.json { render :json => @events}
    end
  end

  def please_confirm
    render :layout => 'confirm'
  end

  def date

    @events = Kaminari.paginate_array(Event.find(:all, :conditions => ["DATE(eventdate) = ?", Date.parse("#{params[:date]['day']}-#{params[:date]['month']}-#{params[:date]['year']}")])).page(params[:page]).per(10)
    
    respond_to do |format|
      format.html # date.html.erb
      format.json { render :json => @events }
    end
  end

  def tomorrow
    @events = Kaminari.paginate_array(Event.find(:all, :conditions => ["DATE(eventdate) = ?", Date.tomorrow])).page(params[:page]).per(20)
    
    respond_to do |format|
      format.html # tomorrow.html.erb
      format.json { render :json => @events }
    end
  end

  def recent
    @events = Kaminari.paginate_array(Event.find(:all, :order => 'created_at DESC', :conditions => ["DATE(eventdate) > ?", Date.today-1])).page(params[:page]).per(10)
    
    respond_to do |format|
      format.html # recent.html.erb
      format.json { render :json => @events}
    end
  end

  def today
    @events = Kaminari.paginate_array(Event.find(:all, :conditions => ["DATE(eventdate) = ?", Date.today])).page(params[:page]).per(10)
     
    respond_to do |format|
      format.html # today.html.erb
      format.json { render :json => @events}
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    
    @event = Event.find(params[:id])
    @event.update_attribute(:page_views, @event.page_views + 1) 
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        @event.update_attribute(:user_id, current_user.id)
        format.html { redirect_to @event, :notice => 'Event was successfully created.' }
        format.json { render :json => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, :notice => 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    @event = nil	
    respond_to do |format|
      format.html { redirect_to events_url, :notice => "Event successfully deleted." }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout 'home_layout'

  def index
    if current_user
      redirect_to events_url
    end
  end

  def new
  end

end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @notices }
    end
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
    @notice = Notice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @notice }
    end
  end

  # GET /notices/new
  # GET /notices/new.json
  def new
    @notice = Notice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @notice }
    end
  end

  # GET /notices/1/edit
  def edit
    @notice = Notice.find(params[:id])
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(params[:notice])

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, :notice => 'Notice was successfully created.' }
        format.json { render :json => @notice, :status => :created, :location => @notice }
      else
        format.html { render :action => "new" }
        format.json { render :json => @notice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notices/1
  # PUT /notices/1.json
  def update
    @notice = Notice.find(params[:id])

    respond_to do |format|
      if @notice.update_attributes(params[:notice])
        format.html { redirect_to @notice, :notice => 'Notice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @notice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice = Notice.find(params[:id])
    @notice.destroy

    respond_to do |format|
      format.html { redirect_to notices_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

layout 'confirm'

def sign_in

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="new_event_wrapper">
  <div class="new_event_datetime_wrapper">
  <div class="field">
    <div class="event_label">
    <div class="new_event_date">
    </div>
    </div>
    <div class="event_field">
    <div class="new_event_date">
    <%= f.date_select :eventdate, :order => [:month, :day, :year] %>
    </div>
    </div>
  </div>
  </div>
  <div class="field">
    <div class="event_field">
    <div class="new_event_time">
    <%= f.time_select :eventtime, {:ampm => true, :minute_step => 5} %>
    </div>
    </div>
  </div>
  </div>
  <div class="new_event_name_wrapper">
  <div class="field">
    <div class="event_label">
    <div class="new_event_name">
    </div>
    </div>
    <div class="event_field">
    <%= f.text_field :name, :placeholder => "Name", :class => "new_event_name_field" %>
    </div>
  </div>
  </div>
  <div class="new_event_location_wrapper">
  <div class="field">
    <div class="event_label">
    <div class="new_event_location">
    </div>
    </div>
    <div class="event_field">
    <%= f.text_field :location, :placeholder => "Where?", :class => "new_event_location_field" %>
    </div>
  </div>
  </div>
  
  <div class="field">
    <div class="event_label">
    <div class="new_event_description">
    </div>
    </div>
    <div class="event_field">
    <%= f.text_area :description, :class => "new_event_description_field", :placeholder => "Description" %>
    </div>
  </div>
   
  <div class="actions">
    <%= f.submit "Post it", :class => "new_event_submit"  %>
  </div>
  </div>
<% end %>

app/views/events/date.html.erb
<div id="event_listings_container" class="event_listings">	
  <ul id="navmenu">
    <li><a href="../events"><strong>Popular</strong></a></li>
    <li><a href="../events/recent">New</a></li>
    <li><a href="../events/today">Today</a></li>
    <li><%= form_tag date_events_path, :method => 'get', :class => "date_form" do %>
					<%= select_date(Time.now, :order => [:month, :day, :year])  %>
					<%= submit_tag "Filter Events by Date", :name => :nil, :class => "date_bar_button" %>
				    <% end %></li>
    <li><span id="search"><%= form_tag search_events_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search], :class => "search_bar", :placeholder => "Search"  %>
        <% end %></span>
    </li>

  </ul>


  <div id="pagination"><%= paginate @events %></div>	  
  <% @events.each do |event| %>
  <ul id="events">
   
    <li class="event_listings_item">
      <a class="event_listings_item_link" href="/events/<%= event.id %>">
      <ul>
        <li class="event_name"><%= truncate(event.name, :length => 32, :separator => ' ', :omission => "...") %></li>
        <li class="event_location"><%= truncate(event.location, :length => 50, :separator => ' ', :omission => "...") %></li>
        <li class="event_datetime"><%= event.eventtime.strftime("%I:%M%p") %> on <%= event.eventdate.strftime("%m/%d/%Y") %></li>
        <li class="event_description"><%= truncate(event.description, :length => 153, :separator => ' ', :omission => "...\n") %></li>
      </ul>
    </a>
    </li>
    <% end %>
  </ul>
</div>
		

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div id="event_listings_container" class="event_listings">	
  <ul id="navmenu">
    <li><a href="../events"><strong>Popular</strong></a></li>
    <li><a href="../events/recent">New</a></li>
    <li><a href="../events/today">Today</a></li>
    <li><%= form_tag date_events_path, :method => 'get', :class => "date_form" do %>
					<%= select_date(Time.now, :order => [:month, :day, :year])  %>
					<%= submit_tag "Filter Events by Date", :name => :nil, :class => "date_bar_button" %>
				    <% end %></li>
    <li><span id="search"><%= form_tag search_events_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search], :class => "search_bar", :placeholder => "Search"  %>
        <% end %></span>
    </li>

  </ul>
		  
  <% @events.each do |event| %>
  <ul id="events">
    <li class="event_listings_item">
      <a class="event_listings_item_link" href="/events/<%= event.id %>">
      <ul>
        <li class="event_name"><%= truncate(event.name, :length => 32, :separator => ' ', :omission => "...") %></li>
        <li class="event_location"><%= truncate(event.location, :length => 50, :separator => ' ', :omission => "...") %></li>
        <li class="event_datetime"><%= event.eventtime.strftime("%I:%M%p") %> on <%= event.eventdate.strftime("%m/%d/%Y") %></li>
        <li class="event_description"><%= truncate(event.description, :length => 153, :separator => ' ', :omission => "...\n") %></li>
      </ul>
    </a>
    </li>
    <% end %>
  </ul>
</div>
		

app/views/events/new.html.erb
<div id="new_event_form">
<%= render 'form' %>
</div>

app/views/events/recent.html.erb
<div id="event_listings_container" class="event_listings">	
  <ul id="navmenu">
    <li><a href="../events">Popular</a></li>
    <li><a href="../events/recent"><strong>New</strong></a></li>
    <li><a href="../events/today">Today</a></li>
    <li><%= form_tag date_events_path, :method => 'get', :class => "date_form" do %>
					<%= select_date(Time.now, :order => [:month, :day, :year])  %>
					<%= submit_tag "Filter Events by Date", :name => :nil, :class => "date_bar_button" %>
				    <% end %></li>

    <li><span id="search"><%= form_tag search_events_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search], :class => "search_bar", :placeholder => "Search"  %>
        <% end %></span>
    </li>

  </ul>
		  
  <div id="pagination"><%= paginate @events %></div>
  <% @events.each do |event| %>
  <ul id="events">
    <li class="event_listings_item">
    <a class="event_listings_item_link" href="/events/<%= event.id %>">
    <ul>
      <li class="event_name"><%= truncate(event.name, :length => 32, :separator => ' ', :omission => "...") %></li>
      <li class="event_location"><%= truncate(event.location, :length => 50, :separator => ' ', :omission => "...") %></li>
      <li class="event_datetime"><%= event.eventtime.strftime("%I:%M%p") %> on <%= event.eventdate.strftime("%m/%d/%Y") %></li>
      <li class="event_description"><%= truncate(event.description, :length => 153, :separator => ' ', :omission => "...\n") %></li>
    </ul>
    </a>
    </li>
    <% end %>
    </ul>
</div>
		

app/views/events/search.html.erb
<div id="event_listings_container" class="event_listings">	
  <ul id="navmenu">
    <li><a href="../events">Popular</a></li>
    <li><a href="../events/recent">New</a></li>
    <li><a href="../events/today">Today</a></li>
    <li><%= form_tag date_events_path, :method => 'get', :class => "date_form" do %>
					<%= select_date(Time.now, :order => [:month, :day, :year])  %>
					<%= submit_tag "Filter Events by Date", :name => :nil, :class => "date_bar_button" %>
				    <% end %></li>

    <li><span id="search"><%= form_tag search_events_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search], :class => "search_bar", :placeholder => "Search"  %>
        <% end %></span>
    </li>

  </ul>
		  
  <div id="pagination"><%= paginate @events %></div>
  <% @events.each do |event| %>
  <ul id="events">
    <li class="event_listings_item">
    <a class="event_listings_item_link" href="/events/<%= event.id %>">
    <ul>
      <li class="event_name"><%= truncate(event.name, :length => 32, :separator => ' ', :omission => "...") %></li>
      <li class="event_location"><%= truncate(event.location, :length => 50, :separator => ' ', :omission => "...") %></li>
      <li class="event_datetime"><%= event.eventtime.strftime("%I:%M%p") %> on <%= event.eventdate.strftime("%m/%d/%Y") %></li>
      <li class="event_description"><%= truncate(event.description, :length => 153, :separator => ' ', :omission => "...\n") %></li>
    </ul>
    </a>
    </li>
    <% end %>
    </ul>
</div>
		

app/views/events/show.html.erb
<div id="events_info">
  <div id="events_info_container">
  <div id="events_info_title"><%= @event.name %> </div>
  <div id="events_info_datetime"><%= @event.eventdate.strftime("%m/%d/%Y") %> at <%= @event.eventtime.strftime("%I:%M%p") %></div>
  <div id="events_info_location"><%= @event.location %></div>
  <p id="events_info_description"><%= h(@event.description).gsub(/\n/, '<br/>').html_safe %> </p>
  <% if @event.user.email == current_user.email %>
  <%= button_to "Delete", @event, :method => :delete, :confirm => "Are you sure? This event will be permanently deleted." %>
  <br>
  <% end %>
  <%= link_to 'Back to Events', events_path, :id => "back_to_events" %>
  </div>
</div>
</div>

app/views/events/today.html.erb
<div id="event_listings_container" class="event_listings">	
  <ul id="navmenu">
    <li><a href="../events">Popular</a></li>
    <li><a href="../events/recent">New</a></li>
    <li><a href="../events/today"><strong>Today</strong></a></li>
    <li><%= form_tag date_events_path, :method => 'get', :class => "date_form" do %>
					<%= select_date(Time.now, :order => [:month, :day, :year])  %>
					<%= submit_tag "Filter Events by Date", :name => :nil, :class => "date_bar_button" %>
				    <% end %></li>

    <li><span id="search"><%= form_tag search_events_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search], :class => "search_bar", :placeholder => "Search"  %>
        <% end %></span>
    </li>

  </ul>
		  
  <div id="pagination"><%= paginate @events %></div>
  <% @events.each do |event| %>
  <ul id="events">
    <li class="event_listings_item">
    <a class="event_listings_item_link" href="/events/<%= event.id %>">
    <ul>
      <li class="event_name"><%= truncate(event.name, :length => 32, :separator => ' ', :omission => "...") %></li>
      <li class="event_location"><%= truncate(event.location, :length => 50, :separator => ' ', :omission => "...") %></li>
      <li class="event_datetime"><%= event.eventtime.strftime("%I:%M%p") %> on <%= event.eventdate.strftime("%m/%d/%Y") %></li>
      <li class="event_description"><%= truncate(event.description, :length => 153, :separator => ' ', :omission => "...\n") %></li>
    </ul>
    </a>
    </li>
    <% end %>
    </ul>
</div>
		

app/views/home/index.html.erb
<div id="header">
  <div id="homepage_login">
    <%= form_for("user", :url => user_session_path) do |f| %>
      <%= f.submit "Sign in", :id => "homepage_login_submit" %>
      <%= f.password_field :password , :size=>'15', :maxlength=>'32', :placeholder => "Password", :tabindex => 2, :id => "homepage_login_password_bar" %>
      <%= f.text_field :email , :size=>'15',:maxlength=>'32', :placeholder => "Email", :tabindex => 1, :id => "homepage_login_email_bar" %>
    <% end %>
  </div>
</div>
  
<div id="logo_home"><%= image_tag 'logo_home.png' %></div>

<div id="content">
  <div id="pitch">
    <h3>What's happening on your campus?</h3>
      <p id="tagline">One website. &nbsp;Every event imaginable.</p>
      <ul id="description">
      <li></li>
      <li>Create and broadcast your own events. Find new clubs, study groups and activities. Exclusively for your university.</li>
      <li><strong>Only on Dormtown.</strong></li>
      </p>

      <div id="students">
        <p><strong>New to Dormtown?</strong> Sign up with a valid Pitt.edu email address.</p>
        <hr />
        <%= form_for("user", :url => user_registration_path, :html => { :onsubmit => 'afterSignup(); return true;' } ) do |f| %>
          <div><%= f.label 'University email' %><br />
          <%= f.email_field :email, :id => "homepage_register_email_bar" %></div>
          <div><%= f.label :password %><br />
          <%= f.password_field :password, :id => "homepage_register_password_bar" %></div>

          <div><%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, :id => "homepage_register_password_confirmation_bar" %></div>

          <div><%= f.submit "Sign up", :id => "homepage_register_submit" %></div>
          <% end %>
      </div>
    </div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Dormtown - What's happening on your campus?</title>
	<%= stylesheet_link_tag "school_style", "normalize" %>
	<%= javascript_include_tag "application", "jquery-1.9.1" %>
	<%= csrf_meta_tag %>	
	<%= favicon_link_tag 'favicon.ico' %>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38877340-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
	<div id="header">
	  <ul>
	    <li id="logo"><%= link_to (image_tag "logo.png"), events_url %></li>
            <% if user_signed_in? %>
	    <li id="user_account"><%= current_user.email %><%= link_to "Sign out", destroy_user_session_path, :id => "user_account_signout" %></li>
            <% end %>   
	  </ul>
	</div>

	<div id="container">
	  <div id="tagpost">
	    <h1>What's happening at Pitt?</h1>
	    <div id="post_container"><%= link_to 'Post something', new_event_path, :id => "post"%></div>
	  </div>		
	<%= yield %>

<div id="footer">
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Dormtown - What's happening at your campus?</title>
	<%= stylesheet_link_tag "school_style", "normalize" %>
	<%= javascript_include_tag "application", "jquery-1.9.1" %>
	<%= csrf_meta_tag %>	
</head>
<body>
	<div id="header">
	  <ul>
	    <li id="logo"><%= link_to (image_tag "logo.png"), events_url %></li>
               
	  </ul>
	</div>

	<div id="container">
	  <div id="tagpost">
	    <h1>Please log in to continue to Dormtown.</h1>
	  </div>		
	<%= yield %>

</body>
</html>

app/views/layouts/home_layout.html.erb
<html>
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Dormtown - What's happening on your campus?</title>
        <meta name="generator" content="TextMate http://macromates.com/">
        <meta name="author" content="keifer">
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
        <%= stylesheet_link_tag "homepage_style" %>
	<%= javascript_include_tag "application" %>	
	<%= favicon_link_tag 'favicon.ico' %>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38877340-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>
<body>

<%= yield %>
</body>
</html>

app/views/notices/_form.html.erb
<%= form_for(@notice) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @notice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing notice</h1>

<%= render 'form' %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<h1>Listing notices</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Contact</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notices.each do |notice| %>
  <tr>
    <td><%= notice.name %></td>
    <td><%= notice.location %></td>
    <td><%= notice.contact %></td>
    <td><%= notice.description %></td>
    <td><%= link_to 'Show', notice %></td>
    <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
    <td><%= link_to 'Destroy', notice, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New notice</h1>

<%= render 'form' %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @notice.name %>
</p>

<p>
  <b>Location:</b>
  <%= @notice.location %>
</p>

<p>
  <b>Contact:</b>
  <%= @notice.contact %>
</p>

<p>
  <b>Description:</b>
  <%= @notice.description %>
</p>


<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>

app/views/users/show.html.erb
<%= @user.email %>